#!/usr/bin/env python3

import yaml, os
from tqdm.auto import tqdm

def generate_profile(name: str, directory: str) -> None:
    path = os.path.join(directory, f'{name.lower()}.md')
    if os.path.exists(path):
        return

    profile = {'author': name, 'permalink': f'/team/{name.lower().replace(" ", "+")}'}
    content = f'---\n{yaml.dump(profile, default_flow_style=False)}---'
    with open(path, 'w') as f:
        f.write(content)


if __name__ == "__main__":
    root = os.environ.get('DATA_ROOT', '.')
    with open(os.path.join(root, '_data/authors.yml')) as f:
        authors = yaml.load(f, Loader=yaml.FullLoader)

    pbar = tqdm(authors)
    for name in pbar:
        pbar.set_description(name)
        generate_profile(name, os.path.join(root, '_members'))